package com.ims.orm.common;

public enum EntitlementType {

    NONE, ALL_TENANT_USERS, ORGS, GROUPS, USERS, OWNER, PUBLIC, CUSTOM, GRID,GLOBAL,
    ALL_BLUEPRINTS, MY_BLUEPRINTS, CUSTOM_BLUEPRINTS,ALL_PLUGINS, MY_PLUGINS, CUSTOM_PLUGINS, TENANTS, TENANTS_CUSTOM;

}