-- Table: BLUEPRINT, PROVISION, DOCKER_SERVER

-- Adding a new Column LICENSE_MODEL  -  Valid values: LICENSE_INCLUDED or BRING_YOUR_OWN_LICENSE

ALTER TABLE BLUEPRINT ADD COLUMN LICENSE_MODEL character varying(510);
ALTER TABLE PROVISION ADD COLUMN LICENSE_MODEL character varying(510);
ALTER TABLE DOCKER_SERVER ADD COLUMN LICENSE_MODEL character varying(510);

-- Solr not indexed so this will work.
UPDATE BLUEPRINT SET LICENSE_MODEL = 'LICENSE_INCLUDED' WHERE LICENSE_MODEL is null;
UPDATE PROVISION SET LICENSE_MODEL = 'LICENSE_INCLUDED' WHERE LICENSE_MODEL is null;
UPDATE DOCKER_SERVER SET LICENSE_MODEL = 'LICENSE_INCLUDED' WHERE LICENSE_MODEL is null;
