
-- Author: Syed Zainul Abedeen (sabedeen@hypergrid.com)
ALTER TABLE machine_type add COLUMN cloud_group character varying(255);

INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (1,'Standard_B1s','General Purpose','AZURE','1',1,'4');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (2,'Standard_B1ms','General Purpose','AZURE','1',2,'4');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (3,'Standard_B2s','General Purpose','AZURE','2',4,'8');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (4,'Standard_B2ms','General Purpose','AZURE','2',8,'16');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (5,'Standard_B4ms','General Purpose','AZURE','4',16,'32');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (6,'Standard_B8ms','General Purpose','AZURE','8',32,'64');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (7,'Standard_D2s_v3','General Purpose','AZURE','2',8,'16');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (8,'Standard_D4s_v3','General Purpose','AZURE','4',16,'32');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (9,'Standard_D8s_v3','General Purpose','AZURE','8',32,'64');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (10,'Standard_D16s_v3','General Purpose','AZURE','16',64,'128');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (11,'Standard_D32s_v3','General Purpose','AZURE','32',128,'256');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (12,'Standard_D64s_v3','General Purpose','AZURE','64',256,'512');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (13,'Standard_D2_v3','General Purpose','AZURE','2',8,'50');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (14,'Standard_D4_v3','General Purpose','AZURE','4',16,'100');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (15,'Standard_D8_v3','General Purpose','AZURE','8',32,'200');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (16,'Standard_D16_v3','General Purpose','AZURE','16',64,'400');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (17,'Standard_D32_v3','General Purpose','AZURE','32',128,'800');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (18,'Standard_D64_v3','General Purpose','AZURE','64',256,'1600');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (19,'Standard_DS1_v2','General Purpose','AZURE','1',3.5,'7');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (20,'Standard_DS2_v2','General Purpose','AZURE','2',7,'14');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (21,'Standard_DS3_v2','General Purpose','AZURE','4',14,'28');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (22,'Standard_DS4_v2','General Purpose','AZURE','8',28,'56');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (23,'Standard_DS5_v2','General Purpose','AZURE','16',56,'112');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (24,'Standard_D1_v2','General Purpose','AZURE','1',3.5,'50');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (25,'Standard_D2_v2','General Purpose','AZURE','2',7,'100');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (26,'Standard_D3_v2','General Purpose','AZURE','4',14,'200');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (27,'Standard_D4_v2','General Purpose','AZURE','8',28,'400');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (28,'Standard_D5_v2','General Purpose','AZURE','16',56,'800');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (29,'Standard_DS1','General Purpose','AZURE','1',3.5,'7');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (30,'Standard_DS2','General Purpose','AZURE','2',7,'14');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (31,'Standard_DS3','General Purpose','AZURE','4',14,'28');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (32,'Standard_DS4','General Purpose','AZURE','8',28,'56');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (33,'Standard_D1','General Purpose','AZURE','1',3.5,'50');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (34,'Standard_D2','General Purpose','AZURE','2',7,'100');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (35,'Standard_D3','General Purpose','AZURE','4',14,'200');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (36,'Standard_D4','General Purpose','AZURE','8',28,'400');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (37,'Standard_A1_v2','General Purpose','AZURE','1',2,'10');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (38,'Standard_A2_v2','General Purpose','AZURE','2',4,'20');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (39,'Standard_A4_v2','General Purpose','AZURE','4',8,'40');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (40,'Standard_A8_v2','General Purpose','AZURE','8',16,'80');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (41,'Standard_A2m_v2','General Purpose','AZURE','2',16,'20');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (42,'Standard_A4m_v2','General Purpose','AZURE','4',32,'40');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (43,'Standard_A8m_v2','General Purpose','AZURE','8',64,'80');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (44,'Standard_A0','General Purpose','AZURE','1',0.768,'20');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (45,'Standard_A1','General Purpose','AZURE','1',1.75,'70');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (46,'Standard_A2','General Purpose','AZURE','2',3.5,'135');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (47,'Standard_A3','General Purpose','AZURE','4',7,'285');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (48,'Standard_A4','General Purpose','AZURE','8',14,'605');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (49,'Standard_A5','General Purpose','AZURE','2',14,'135');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (50,'Standard_A6','General Purpose','AZURE','4',28,'285');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (51,'Standard_A7','General Purpose','AZURE','8',56,'605');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (52,'A0\Basic_A0','General Purpose','AZURE','1',768,'20');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (53,'A1\Basic_A1','General Purpose','AZURE','1',1.75,'40');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (54,'A2\Basic_A2','General Purpose','AZURE','2',3.5,'60');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (55,'A3\Basic_A3','General Purpose','AZURE','4',7,'120');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (56,'A4\Basic_A4','General Purpose','AZURE','8',14,'240');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (57,'Standard_F2s_v2','COMPUTE OPTIMIZED','AZURE','2',4,'16');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (58,'Standard_F4s_v2','COMPUTE OPTIMIZED','AZURE','4',8,'32');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (59,'Standard_F8s_v2','COMPUTE OPTIMIZED','AZURE','8',16,'64');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (60,'Standard_F16s_v2','COMPUTE OPTIMIZED','AZURE','16',32,'128');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (61,'Standard_F32s_v2','COMPUTE OPTIMIZED','AZURE','32',64,'256');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (62,'Standard_F64s_v2','COMPUTE OPTIMIZED','AZURE','64',128,'512');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (63,'Standard_F72s_v2','COMPUTE OPTIMIZED','AZURE','72',144,'576');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (64,'Standard_F1s','COMPUTE OPTIMIZED','AZURE','1',2,'4');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (65,'Standard_F2s','COMPUTE OPTIMIZED','AZURE','2',4,'8');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (66,'Standard_F4s','COMPUTE OPTIMIZED','AZURE','4',8,'16');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (67,'Standard_F8s','COMPUTE OPTIMIZED','AZURE','8',16,'32');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (68,'Standard_F16s','COMPUTE OPTIMIZED','AZURE','16',32,'64');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (69,'Standard_F1','COMPUTE OPTIMIZED','AZURE','1',2,'16');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (70,'Standard_F2','COMPUTE OPTIMIZED','AZURE','2',4,'32');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (71,'Standard_F4','COMPUTE OPTIMIZED','AZURE','4',8,'64');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (72,'Standard_F8','COMPUTE OPTIMIZED','AZURE','8',16,'128');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (73,'Standard_F16','COMPUTE OPTIMIZED','AZURE','16',32,'256');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (74,'Standard_E2s_v3','Memory Optimized','AZURE','2',16,'32');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (75,'Standard_E4s_v3','Memory Optimized','AZURE','4',32,'64');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (76,'Standard_E8s_v3','Memory Optimized','AZURE','8',64,'128');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (77,'Standard_E16s_v3','Memory Optimized','AZURE','16',128,'256');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (78,'Standard_E32s_v3','Memory Optimized','AZURE','32',256,'512');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (79,'Standard_E64s_v3','Memory Optimized','AZURE','64',432,'864');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (80,'Standard_E2_v3','Memory Optimized','AZURE','2',16,'50');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (81,'Standard_E4_v3','Memory Optimized','AZURE','4',32,'100');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (82,'Standard_E8_v3','Memory Optimized','AZURE','8',64,'200');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (83,'Standard_E16_v3','Memory Optimized','AZURE','16',128,'400');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (84,'Standard_E32_v3','Memory Optimized','AZURE','32',256,'800');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (85,'Standard_E64_v3','Memory Optimized','AZURE','64',432,'1600');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (86,'Standard_M64s','Memory Optimized','AZURE','64',1024,'2048');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (87,'Standard_M64ms','Memory Optimized','AZURE','64',1792,'2048');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (88,'Standard_M128s','Memory Optimized','AZURE','128',2048,'4096');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (89,'Standard_M128ms','Memory Optimized','AZURE','128',3800,'4096');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (90,'Standard_GS1','Memory Optimized','AZURE','2',28,'56');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (91,'Standard_GS2','Memory Optimized','AZURE','4',56,'112');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (92,'Standard_GS3','Memory Optimized','AZURE','8',112,'224');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (93,'Standard_GS4','Memory Optimized','AZURE','16',224,'448');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (94,'Standard_GS5','Memory Optimized','AZURE','32',448,'896');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (95,'Standard_G1','Memory Optimized','AZURE','2',28,'384');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (96,'Standard_G2','Memory Optimized','AZURE','4',56,'768');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (97,'Standard_G3','Memory Optimized','AZURE','8',112,'1536');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (98,'Standard_G4','Memory Optimized','AZURE','16',224,'3072');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (99,'Standard_G5','Memory Optimized','AZURE','32',448,'6144');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (100,'Standard_DS11_v2','Memory Optimized','AZURE','2',14,'28');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (101,'Standard_DS12_v2','Memory Optimized','AZURE','4',28,'56');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (102,'Standard_DS13_v2','Memory Optimized','AZURE','8',56,'112');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (103,'Standard_DS14_v2','Memory Optimized','AZURE','16',112,'224');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (104,'Standard_DS15_v2','Memory Optimized','AZURE','20',140,'280');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (105,'Standard_D11_v2','Memory Optimized','AZURE','2',14,'100');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (106,'Standard_D12_v2','Memory Optimized','AZURE','4',28,'200');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (107,'Standard_D13_v2','Memory Optimized','AZURE','8',56,'400');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (108,'Standard_D14_v2','Memory Optimized','AZURE','16',112,'800');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (109,'Standard_D15_v2','Memory Optimized','AZURE','20',140,'1000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (110,'Standard_DS11','Memory Optimized','AZURE','2',14,'28');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (111,'Standard_DS12','Memory Optimized','AZURE','4',28,'56');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (112,'Standard_DS13','Memory Optimized','AZURE','8',56,'112');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (113,'Standard_DS14','Memory Optimized','AZURE','16',112,'224');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (114,'Standard_D11','Memory Optimized','AZURE','2',14,'100');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (115,'Standard_D12','Memory Optimized','AZURE','4',28,'200');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (116,'Standard_D13','Memory Optimized','AZURE','8',56,'400');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (117,'Standard_D14','Memory Optimized','AZURE','16',112,'800');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (118,'Standard_L4s','Storage Optimized','AZURE','4',32,'678');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (119,'Standard_L8s','Storage Optimized','AZURE','8',64,'1388');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (120,'Standard_L16s','Storage Optimized','AZURE','16',128,'2807');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (121,'Standard_L32s','Storage Optimized','AZURE','32',256,'5630');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (122,'Standard_NC6','GPU Optimized','AZURE','6',56,'380');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (123,'Standard_NC12','GPU Optimized','AZURE','12',112,'680');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (124,'Standard_NC24','GPU Optimized','AZURE','24',224,'1440');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (125,'Standard_NC24r','GPU Optimized','AZURE','24',224,'1440');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (126,'Standard_NC6_v2','GPU Optimized','AZURE','6',112,'336');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (127,'Standard_NC12_v2','GPU Optimized','AZURE','12',224,'672');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (128,'Standard_NC24_v2','GPU Optimized','AZURE','24',448,'1344');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (129,'Standard_NC24r_v2','GPU Optimized','AZURE','24',1448,'1344');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (130,'Standard_ND6','GPU Optimized','AZURE','6',112,'336');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (131,'Standard_ND12','GPU Optimized','AZURE','12',224,'672');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (132,'Standard_ND24','GPU Optimized','AZURE','24',448,'1344');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (133,'Standard_ND24r','GPU Optimized','AZURE','24',1448,'1344');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (134,'Standard_NV6','GPU Optimized','AZURE','6',56,'380');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (135,'Standard_NV12','GPU Optimized','AZURE','12',112,'680');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (136,'Standard_NV24','GPU Optimized','AZURE','24',224,'1440');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (137,'Standard_H8','High Performance','AZURE','8',56,'1000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (138,'Standard_H16','High Performance','AZURE','16',112,'2000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (139,'Standard_H8m','High Performance','AZURE','8',112,'1000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (140,'Standard_H16m','High Performance','AZURE','16',224,'2000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (141,'Standard_H16r','High Performance','AZURE','16',112,'2000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (142,'Standard_H16mr','High Performance','AZURE','16',224,'2000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (143,'Standard_A8','High Performance','AZURE','8',56,'382');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (144,'Standard_A9','High Performance','AZURE','16',112,'382');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (145,'Standard_A10','High Performance','AZURE','8',56,'382');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (146,'Standard_A11','High Performance','AZURE','16',112,'382');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (147,'n1-standard-1','Standard','GOOGLE','1',3.75,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (148,'n1-standard-2','Standard','GOOGLE','2',7.5,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (149,'n1-standard-4','Standard','GOOGLE','4',15,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (150,'n1-standard-8','Standard','GOOGLE','8',30,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (151,'n1-standard-16','Standard','GOOGLE','16',60,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (152,'n1-standard-32','Standard','GOOGLE','32',120,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (153,'n1-standard-64','Standard','GOOGLE','64',240,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (154,'n1-standard-96 (Beta)','Standard','GOOGLE','96',360,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (155,'n1-highmem-2','Hihg Memory','GOOGLE','2',13,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (156,'n1-highmem-4','Hihg Memory','GOOGLE','4',26,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (157,'n1-highmem-8','Hihg Memory','GOOGLE','8',52,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (158,'n1-highmem-16','Hihg Memory','GOOGLE','16',104,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (159,'n1-highmem-32','Hihg Memory','GOOGLE','32',208,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (160,'n1-highmem-64','Hihg Memory','GOOGLE','64',416,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (161,'n1-highmem-96 (Beta)','Hihg Memory','GOOGLE','96',624,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (162,'n1-highcpu-2','High CPU','GOOGLE','2',1.8,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (163,'n1-highcpu-4','High CPU','GOOGLE','4',3.6,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (164,'n1-highcpu-8','High CPU','GOOGLE','8',7.2,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (165,'n1-highcpu-16','High CPU','GOOGLE','16',14.4,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (166,'n1-highcpu-32','High CPU','GOOGLE','32',28.8,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (167,'n1-highcpu-64','High CPU','GOOGLE','64',57.6,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (168,'n1-highcpu-96 (Beta)','High CPU','GOOGLE','96',86.4,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (169,'f1-micro','F1 Micro Bursting','GOOGLE','0.2',0.6,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (170,'g1-small','F1 Micro Bursting','GOOGLE','0.5',1.7,NULL);
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (171,'t2.nano','General Purpose','AWS','1',0.5,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (172,'t2.micro','General Purpose','AWS','1',1,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (173,'t2.small','General Purpose','AWS','1',2,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (174,'t2.medium','General Purpose','AWS','2',4,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (175,'t2.large','General Purpose','AWS','2',8,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (176,'t2.xlarge','General Purpose','AWS','4',16,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (177,'t2.2xlarge','General Purpose','AWS','8',32,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (178,'m5. large','General Purpose','AWS','2',8,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (179,'m5.xlarge','General Purpose','AWS','4',16,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (180,'m5.2xlarge','General Purpose','AWS','8',32,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (181,'m5.4xlarge','General Purpose','AWS','16',64,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (182,'m5.12xlarge','General Purpose','AWS','48',192,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (183,'m5.24xlarge','General Purpose','AWS','96',384,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (184,'m4.large','General Purpose','AWS','2',8,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (185,'m4.xlarge','General Purpose','AWS','4',16,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (186,'m4.2xlarge','General Purpose','AWS','8',32,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (187,'m4.4xlarge','General Purpose','AWS','16',64,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (188,'m4.10xlarge','General Purpose','AWS','40',160,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (189,'m4.16xlarge','General Purpose','AWS','64',256,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (190,'m3.medium','General Purpose','AWS','1',3.75,'1 x 4 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (191,'m3.large','General Purpose','AWS','2',7.5,'1 x 32 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (192,'m3.xlarge','General Purpose','AWS','4',15,'2 x 40 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (193,'m3.2xlarge','General Purpose','AWS','8',30,'2 x 80 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (194,'c5.large','Compute Optimized','AWS','2',4,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (195,'c5.xlarge','Compute Optimized','AWS','4',8,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (196,'c5.2xlarge','Compute Optimized','AWS','8',16,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (197,'c5.4xlarge','Compute Optimized','AWS','16',32,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (198,'c5.9xlarge','Compute Optimized','AWS','36',72,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (199,'c5.18xlarge','Compute Optimized','AWS','72',144,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (200,'c4.large','Compute Optimized','AWS','2',3.75,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (201,'c4.xlarge','Compute Optimized','AWS','4',7.5,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (202,'c4.2xlarge','Compute Optimized','AWS','8',15,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (203,'c4.4xlarge','Compute Optimized','AWS','16',30,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (204,'c4.8xlarge','Compute Optimized','AWS','36',60,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (205,'c3.large','Compute Optimized','AWS','2',3.75,'2 x 16 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (206,'c3.xlarge','Compute Optimized','AWS','4',7.5,'2 x 40 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (207,'c3.2xlarge','Compute Optimized','AWS','8',15,'2 x 80 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (208,'c3.4xlarge','Compute Optimized','AWS','16',30,'2 x 160 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (209,'c3.8xlarge','Compute Optimized','AWS','32',60,'2 x 320 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (210,'x1.16xlarge','Memory Optimized','AWS','64',976,'1 x 1,920 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (211,'x1.32xlarge','Memory Optimized','AWS','128',1952,'2 x 1,920 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (212,'x1e.xlarge','Memory Optimized','AWS','4',122,'1 x 120 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (213,'x1e.2xlarge','Memory Optimized','AWS','8',244,'1 x 240 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (214,'x1e.4xlarge','Memory Optimized','AWS','16',488,'1 x 480 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (215,'x1e.8xlarge','Memory Optimized','AWS','32',976,'1 x 960 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (216,'x1e.16xlarge','Memory Optimized','AWS','64',1952,'1 x 1,920 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (217,'x1e.32xlarge','Memory Optimized','AWS','128',3904,'2 x 1,920 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (218,'r4.large','Memory Optimized','AWS','2',15.25,'-');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (219,'r4.xlarge','Memory Optimized','AWS','4',30.5,'-');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (220,'r4.2xlarge','Memory Optimized','AWS','8',61,'-');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (221,'r4.4xlarge','Memory Optimized','AWS','16',122,'-');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (222,'r4.8xlarge','Memory Optimized','AWS','32',244,'-');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (223,'r4.16xlarge','Memory Optimized','AWS','64',488,'-');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (224,'r3.large','Memory Optimized','AWS','2',15.25,'1 x 32 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (225,'r3.xlarge','Memory Optimized','AWS','4',30.5,'1 x 80 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (226,'r3.2xlarge','Memory Optimized','AWS','8',61,'1 x 160 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (227,'r3.4xlarge','Memory Optimized','AWS','16',122,'1 x 320 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (228,'r3.8xlarge','Memory Optimized','AWS','32',244,'2 x 320 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (229,'p3.2xlarge','Accelerated Computing','AWS','8',61,'EBS only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (230,'p3.8xlarge','Accelerated Computing','AWS','32',244,'EBS only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (231,'p3.16xlarge','Accelerated Computing','AWS','64',488,'EBS only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (232,'p2.xlarge','Accelerated Computing','AWS','4',61,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (233,'p2.8xlarge','Accelerated Computing','AWS','32',488,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (234,'p2.16xlarge','Accelerated Computing','AWS','64',732,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (235,'g3.4xlarge','Accelerated Computing','AWS','16',122,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (236,'g3.8xlarge','Accelerated Computing','AWS','32',244,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (237,'g3.16xlarge','Accelerated Computing','AWS','64',488,'EBS Only');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (238,'f1.2xlarge','Accelerated Computing','AWS','8',122,'480 SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (239,'f1.16xlarge','Accelerated Computing','AWS','64',976,'4 x 960');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (240,'h1.2xlarge','Storage Optimized','AWS','8',32,'1 x 2,000 HDD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (241,'h1.4xlarge','Storage Optimized','AWS','16',64,'2 x 2,000 HDD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (242,'h1.8xlarge','Storage Optimized','AWS','32',128,'4 x 2,000 HDD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (243,'h1.16xlarge','Storage Optimized','AWS','64',256,'8 x 2,000 HDD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (244,'i3.large','Storage Optimized','AWS','2',15.25,'1 x 475 NVMe SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (245,'i3.xlarge','Storage Optimized','AWS','4',30.5,'1 x 950 NVMe SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (246,'i3.2xlarge','Storage Optimized','AWS','8',61,'1 x 1,900 NVMe SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (247,'i3.4xlarge','Storage Optimized','AWS','16',122,'2 x 1,900 NVMe SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (248,'i3.8xlarge','Storage Optimized','AWS','32',244,'4 x 1,900 NVMe SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (249,'i3.16xlarge','Storage Optimized','AWS','64',488,'8 x 1,900 NVMe SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (250,'i3.metal','Storage Optimized','AWS','NA',512,'8 x 1.9 NVMe SSD');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (251,'d2.xlarge','Storage Optimized','AWS','4',30.5,'3 x 2000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (252,'d2.2xlarge','Storage Optimized','AWS','8',61,'6 x 2000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (253,'d2.4xlarge','Storage Optimized','AWS','16',122,'12 x 2000');
INSERT INTO machine_type(id,name,cloud_group,cloud,vcpu,mem,disk) VALUES (254,'d2.8xlarge','Storage Optimized','AWS','36',244,'24 x 2000');
commit;