-- Table: USERS

-- Adding a new Column ORG_PUBLIC_PAGE_ENABLED

ALTER TABLE USERS ADD COLUMN ORG_PUBLIC_PAGE_ENABLED BOOLEAN DEFAULT false;

UPDATE USERS SET ORG_PUBLIC_PAGE_ENABLED = FALSE WHERE ORG_PUBLIC_PAGE_ENABLED IS NULL;
