ALTER TABLE activity_log ADD COLUMN ebay_paypal_percent CHARACTER VARYING(255);
ALTER TABLE activity_log ADD COLUMN difference CHARACTER VARYING(255);
ALTER TABLE activity_log ADD COLUMN vat CHARACTER VARYING(255);
ALTER TABLE activity_log ADD COLUMN profit CHARACTER VARYING(255);
ALTER TABLE activity_log ADD COLUMN profit_percentage CHARACTER VARYING(255);