ALTER TABLE accounts ADD COLUMN aws_access_key_id CHARACTER VARYING(255);
ALTER TABLE accounts ADD COLUMN aws_client_secret_id CHARACTER VARYING(255);
ALTER TABLE accounts ADD COLUMN aws_developer_id CHARACTER VARYING(255);
ALTER TABLE accounts ADD COLUMN aws_seller_id CHARACTER VARYING(255);
ALTER TABLE accounts ADD COLUMN aws_market_place_id CHARACTER VARYING(255);
ALTER TABLE accounts ADD COLUMN aws_auth_token CHARACTER VARYING(255);
