ALTER TABLE relist ADD COLUMN title CHARACTER VARYING(255);
ALTER TABLE relist ADD COLUMN sku CHARACTER VARYING(255);
ALTER TABLE relist ADD COLUMN price CHARACTER VARYING(255);
ALTER TABLE relist ADD COLUMN currency CHARACTER VARYING(255);