ALTER TABLE orders ADD COLUMN buyer_street1 CHARACTER VARYING(255);
ALTER TABLE orders ADD COLUMN buyer_street2 CHARACTER VARYING(255);
ALTER TABLE orders ADD COLUMN buyer_city CHARACTER VARYING(255);
ALTER TABLE orders ADD COLUMN buyer_phone_number CHARACTER VARYING(255);
ALTER TABLE orders ADD COLUMN buyer_postal_code CHARACTER VARYING(255);
ALTER TABLE orders ADD COLUMN buyer_state CHARACTER VARYING(255);
ALTER TABLE orders ADD COLUMN buyer_country CHARACTER VARYING(255);
ALTER TABLE orders ADD COLUMN shipping_service_selected CHARACTER VARYING(255);
